float4 main(
	float3 position : POSITION,
	float4 color : COLOR,

	uniform row_major float4x4 u_modelMatrix,
	uniform row_major float4x4 u_viewMatrix,
	uniform row_major float4x4 u_projectionMatrix,

	out float4 pass_color : COLOR ) : POSITION
{
	// Compute the Model-View-Projection matrix
	float4x4 mvp = mul(u_projectionMatrix, mul(u_viewMatrix, u_modelMatrix));

	// Pass the vertex color to the fragment shader
	pass_color = color;

	return mul(mvp, float4(position, 1.0f));
}