//simple clear
float4 main(float2 position) : POSITION
{
	return float4(position.x, position.y, 1.0f, 1.0f);
}

//Will be useful for scissoring and depth clearing
//float4 main(unsigned int idx : INDEX, uniform float4 u_position, uniform float u_clearDepth) : POSITION
//{
//	float x = (idx == 1 || idx == 2) ? u_position[1] : u_position[0];
//	float y = (idx == 2 || idx == 3) ? u_position[3] : u_position[2];
//	return float4(x, y, u_clearDepth, 1.0f);
//}