void main(
	half2 pass_texCoord : TEXCOORD0_HALF,
	uniform sampler2D u_texture,
	out half4 out_color : COLOR)
{
	half4 color = tex2D(u_texture, pass_texCoord);

	// Avoid a branch: if (out_color.a < 1.0f) - shader can stay in parallel mode
	//s = 1 if color.a >= 1, else 0
	half s = step(half(1.0), color.a);

	// factor = 1 when s==1 (opaque)
	//  = 0.5 when s==0 (transparent)
	half factor = half(0.5) * (half(1.0) + s);
	color *= factor;

	out_color = color;
}
