float4 main(
	float3 position,
	float2 texCoord,

	uniform float4x4 u_modelMatrix,
	uniform float4x4 u_viewMatrix,
	uniform float4x4 u_projectionMatrix,

	out float2 pass_texCoord: TEXCOORD0) : POSITION
{
	// Compute the Model-View-Projection matrix
	float4x4 mvp = mul(u_projectionMatrix, mul(u_viewMatrix, u_modelMatrix));
	
	// Pass the texture coordinate to the fragment shader
	pass_texCoord = texCoord;

	return mul(mvp, float4(position, 1.0f));
}
